[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
rps_game = "4S5kqHKSoJEPMutUhUhzcKzC3k7tFsyVnUUMHtyPXxzq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/banana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
